spring.application.name=api
spring.datasource.url=jdbc:mysql://localhost/api_banco
spring.datasource.username=${DB_NAME_API}
spring.datasource.password=${DB_PASSWORD}

#Swagger

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#jpa
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true